### ISSUE TITLE
User story: Add CSP

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/StackPortfolio#189]
### If applicable, add a related Epic.

Epic: 

### User Story

As an IT security specialist, I want to implement Content Security Policy (CSP) to enhance the security posture of our site by reducing the risk of XSS attacks.

### Acceptance Criteria

- CSP is implemented and configured to secure the site.
- Policies are progressively allowed, ensuring minimal disruption to functionality.
- The site is monitored for any issues arising from CSP enforcement.

### Please ensure you've completed these tasks before marking the issue as done.

- [x] Reviewed the user story for clarity and completeness.
- [x] Identified and linked related issues or epics.
- [x] Updated the issue with any relevant notes or feedback (to date).

### Please add any further tasks that need to be completed before the issue can be marked as done.

- [x] Define the CSP policy for the site.
- [x] Check to see what Django already does out of the box.
- [x] Implement CSP in a restrictive mode and gradually adjust the policy to balance security and functionality. (This may require some manual testing).

**Comment by stephendawsondev** [comment]
Hey @KTC96! Giving you this one because you flew through the Django Migration! I wanted to make sure the migration actually took place before we tackled this! 

This one might be a bit more involved because I think it requires understanding what we're adding. I honestly only thought to add this user story after listening to this podcast episode: https://syntax.fm/show/731/client-side-security-xss-attacks-and-csp-with-stripe-s-alex-sexton
I highly recommend listening to it to understand what CSP is, why we need it and how we should approach it (spoiler - it's lock everything down first 😂 ).

Now, with Django 4.2, it might be that there are some CSP things built in, so we may have a lot of this out of the box. I'll be very interested to know what your findings are, so please keep me in the loop!

**Comment by KTC96** [comment]
Sure will take a look at that and challenge my attention span to listen to the podcast!

Will look what CSP features Django has and if/what else we need!

**Comment by KTC96** [comment]
@stephendawsondev Listened to the podcast! Interesting stuff, some of it definitely went over my head though!

From looking online:

- We need to identify what external resources we are using, such as JavaScript libraries, CSS frameworks, fonts, images.
- Define the CSP policy in HTTP header
e.g. 
A website administrator wants all content to come from the site's own origin(blocks everything else). Safest but does not allow anything else to be loaded. 
`Content-Security-Policy: default-src 'self'`
- Implement CSP in Django
From GPT `# csp/middleware.py
class CSPMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        response['Content-Security-Policy'] = "default-src 'self'; script-src 'self' https://example.com;"
        return response
`
- Add to middleware in settings.py
`MIDDLEWARE = [
    ...
    'csp.middleware.CSPMiddleware',
    ...
]`

From the podcast I understand that it is a better policy to block everything and allow what you need, rather than just trying to identify vulnerabilities. Inline styling and scripts can be injected and affect your website to deface as well ad ex filtrating sensitive data. 

There was mention of using CSP in combination with CSP report only when building a web application, so will research into that. 


Good resource I need to read through more : [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)

**Comment by KTC96** [comment]
[Resource control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy)

**Comment by KTC96** [comment]
"To ease deployment, CSP can be deployed in report-only mode. The policy is not enforced, but any violations are reported to a provided URI. Additionally, a report-only header can be used to test a future revision to a policy without actually deploying it."

**Comment by KTC96** [comment]
We could also use  [django-csp](https://django-csp.readthedocs.io/en/latest/)

This could be an easier way for reporting
